export const LOAD_TODOS_SUCCESS = 'App/LOAD_TODOS_SUCCESS';
export const ADD_TODOS = 'App/ADD_TODOS';
export const REFRESHING_TODOS = 'App/REFRESHING_TODOS';
export const TASK_TITLE_CHANGED = 'App/TASK_TITLE_CHANGED';
export const EDIT_TODOS = 'App/EDIT_TODOS';
export const DELETE_TODOS = 'App/DELETE_TODOS';
export const CHANGE_TODO_TYPE = 'App/CHANGE_TODO_TYPE';
export const REHYDRATE = 'persist/REHYDRATE';
//# sourceMappingURL=actionTypes.js.map